name: Generate CRT Contribution SVG

on:
  workflow_dispatch:
  schedule:
    - cron: '15 */12 * * *'

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository, required if the action is in the same repository
      - name: Checkout
        uses: actions/checkout@v5

      - name: Generate & push SVGs
        uses: ./
        with:
          output-dir: assets
          themes: all
